### ISSUE TITLE
Add maximum results returned by a search

### ISSUE THREAD

**Issue by dfq16044** [icatproject/topcat#321] opened 2017-04-10 08:13 UTC
Currently, in the TopCat web interface there is no reference about the maximum number of results returned by a query.
The only to know is using F12.
This was a request from a DLS user, he noticed that the search did not provide all the results that he was expecting.

**Comment by fisherab** [comment] 2017-04-10 13:55
It is not practical to do this. The call from TopCAT to ICAT is limited to a certain number of results - by default 300 I think. All the results returned by ICAT are checked to ensure that the user is authorized to see what they have requested. The number from lucene could be returned but it is meaningless and could be used to count what information the user is not authorised to see which would itself be contrary to the authz rules.

**Comment by dfq16044** [comment] 2017-04-12 08:35
The only change that will need to be performed is showing that the maximum results returned by a search is 300 as this may confuse users if they expect to have more than 300 results.
This number needs to be somewhere in the web interface or the documentation.

**Comment by dfq16044** [comment] 2017-05-23 19:21
Could you please change the label won't fix?

**Comment by jodysalt** [comment] 2017-07-31 15:42
duplicate of #322

**Closed** 2017-07-31 15:42 UTC
Labels: duplicate
