### ISSUE TITLE
Calculating size takes too much time and blocks user interface

### ISSUE THREAD

**Issue by andygotz** [icatproject/topcat#270] opened 2016-08-31 04:55 UTC
Version 2.1.0

There are a number of problems with the Size column:

(1) the Size column displayed for Datasets takes a long time (10s of seconds to minutes) to be calculated. During this time the interface is not responsive. 
(2) The progress bar goes from 0 to 100% and back again multiple times. 
(3) If the files are not on disk any more then the interface can freeze. 
(4) Caching does not seem to be enabled. Going back to the same page the calculation is redone.

It would be better if the size is stored in icat and a single request is made to display it. This might mean adding a new column to the Dataset table but it would be much more efficient and enable a better user experience.

Thank you for fixing this issue.

**Comment by tomgriffinstfc** [comment] 2016-08-31 07:46
If a size column is added to Dataset it may be sensible to do the same for Investigation too.

**Comment by fisherab** [comment] 2016-08-31 08:48
This is a horrible bit of denormalisation. I think it would be better if
TopCAT were less eager to display the information which will take time to
compute.

Steve

**Comment by andygotz** [comment] 2016-08-31 10:36
What we find strange too is that the icat server and the ids are being asked to calculate the size. The request to the icatserver using the COUNT statement is very fast (e.g. 0.02 secs for 1200 files) but what takes a long time is topcat asking for each individual file. Why is this done twice?

**Comment by andygotz** [comment] 2016-08-31 15:33
We have removed the Size column from the interface so we don't have the turning wheels anymore but the progress bar still yoyos and there is a turning circle on the top right hand side. The interface is not responsive when we click on a a dataset or datafile to see the parameters. It seems as even if we do not display the Size column topcat still tries to calculate the size of every file + dataset ...

**Comment by jodysalt** [comment] 2016-09-05 07:18
Hi Andy,

This has already been fixed in the next release (2.20) in issue #208. ;-)

"(1) the Size column displayed for Datasets takes a long time (10s of seconds to minutes) to be calculated. During this time the interface is not responsive."

There is now the concept of low and high priority requests. For low prority ajax requests I only allow a maximum of 2 at anyone time, leaving the rest of the available requests for those that are high priority. I've based the '2' on the following:

http://www.browserscope.org/?category=network&v=top

"(2) The progress bar goes from 0 to 100% and back again multiple times."

This is a bit like a Windows progress bar; it generally doesn't mean much; it is there for psychological reasons i.e. the user knows something is happening. The reason why it goes backwards and forwards is that Topcat maxes out on requests, and when one completes another one comes off the queue and starts reseting the "progress" bar.

"(3) If the files are not on disk any more then the interface can freeze."

So  if files get removed from the IDS the interface will freeze? For Investigations, Datasets and Datafiles? Or do you mean; you are using a two tier system (e.g. tape and disk)  and if the files are not in the cache (i.e. the disk) it crashes?

"(4) Caching does not seem to be enabled. Going back to the same page the calculation is redone."

Do you mean that if you go back to Topcat after closing your browser down things are getSize requests are recalculated? This would be the expected behavior as the IDS doesn't set any caching headers. For getSize requests maybe they should be set.

Topcat does do caching at the javascript level. However, after 10 mins it will remake the request. This should be fine for performing searches; clicking on the results and then using your back button to return to those results.

Jody

**Closed** 2016-09-06 11:33 UTC
