### ISSUE TITLE
Scroll paging navigation info

### ISSUE THREAD

**Issue by wayne-chung** [icatproject/topcat#122] opened 2015-10-19 09:03 UTC
When scroll paging is used, users should be able to see the total number of items and the current numbers or row being displayed in a footer bar at the bottom of the grid. e.g.

```
Showing 1-100 of 955 items
```

**Comment by kevinphippsstfc** [comment] 2015-11-30 15:36
Showing total is more important than current position

**Comment by tomgriffinstfc** [comment] 2016-02-29 11:40
Duplicate of #188

**Closed by tomgriffinstfc** 2016-02-29 11:40 UTC
Labels: enhancement, Priority-Low, TopCAT v2
